Points:
  E-5.0.100-DFA: 1
  E-5.0.101-RE_match: 1
  E-5.1.32-CountMatches: 1
  E-5.1.6-VowelsInOrder: 1
courseID: cs201
hwID: HW13
jpax:
- E-5.0.100-DFA
- E-5.0.101-RE_match
- E-5.1.6-VowelsInOrder
- E-5.1.32-CountMatches
sessionID: CS201
