Points:
  E-2.3.15-BinaryRepresentation: 1
  E-2.3.15-BinaryRepresentation2: 1
  E-2.3.17-Permutation: 1
  E-2.3.17-Permutation_v1: 1
  E-2.3.19-Combination_v1: 1
  E-2.3.2-RecursiveLn: 1
  P-2.3.100-Ruler: 1
  P-2.3.101-Ruler: 1
courseID: cs201
hwID: HW6
jpax:
- E-2.3.2-RecursiveLn
- E-2.3.15-BinaryRepresentation
- E-2.3.15-BinaryRepresentation2
- P-2.3.100-Ruler
- P-2.3.101-Ruler
- E-2.3.19-Combination_v1
- E-2.3.17-Permutation_v1
- E-2.3.17-Permutation
sessionID: CS201
