Points:
  E-1.4.15-Transposing: 1
  E-1.4.17-WeightedAverage: 1
  E-1.4.32-Minesweeper: 1
  E-1.4.33-CheckDuplicate: 1
  E-1.4.38-Birthday: 1
  E-1.4.4-Reverse: 1
courseID: cs201
hwID: HW3
jpax:
- E-1.4.4-Reverse
- E-1.4.15-Transposing
- E-1.4.17-WeightedAverage
- E-1.4.32-Minesweeper
- E-1.4.33-CheckDuplicate
- E-1.4.38-Birthday
sessionID: CS201
