Points:
  E-2.1.103-Tabulate: 1
  E-2.1.16-Scale: 1
  E-2.1.26-EulerFunction: 1
  E-2.2.23-IntegerProperty: 1
courseID: cs201
hwID: HW5
jpax:
- E-2.1.16-Scale
- E-2.1.26-EulerFunction
- E-2.2.23-IntegerProperty
- E-2.1.103-Tabulate
sessionID: CS201
