Points:
  E-1.5.102-HeartCurve: 1
  E-1.5.103-GenerateExpr3: 1
  E-1.5.104-Calculator3: 1
  E-1.5.25-DesignSquares: 1
  E-1.5.3-AverageStd: 1
  E-1.5.8-GeoHarmMean: 1
courseID: cs201
hwID: HW4
jpax:
- E-1.5.3-AverageStd
- E-1.5.8-GeoHarmMean
- E-1.5.25-DesignSquares
- E-1.5.102-HeartCurve
- E-1.5.103-GenerateExpr3
- E-1.5.104-Calculator3
sessionID: CS201
