Points:
  E-3.1.1-Reverse: 1
  E-3.1.10-ComplementWatsonCrick: 1
  E-3.1.11-WCPalindrome: 1
  E-3.1.17-Reversename: 1
  E-3.1.32-Password: 1
  E-3.1.9-DNAchecker: 1
  E-4.1.30-ImproveNo2Slash: 1
courseID: cs201
hwID: HW8
jpax:
- E-3.1.1-Reverse
- E-3.1.9-DNAchecker
- E-3.1.10-ComplementWatsonCrick
- E-3.1.11-WCPalindrome
- E-3.1.17-Reversename
- E-3.1.32-Password
- E-4.1.30-ImproveNo2Slash
sessionID: CS201
