Points:
  E-1.3.1-Equal: 1
  E-1.3.10-NRandomValueAverage: 1
  E-1.3.20-Newton: 1
  E-1.3.36-PrimeCounter: 1
  E-1.3.36-PrimeFactor: 1
  E-1.3.42-Montehall_simplified: 1
  E-1.3.8-nHellos: 1
courseID: cs201
hwID: HW2
jpax:
- E-1.3.1-Equal
- E-1.3.8-nHellos
- E-1.3.10-NRandomValueAverage
- E-1.3.20-Newton
- E-1.3.36-PrimeCounter
- E-1.3.36-PrimeFactor
- E-1.3.42-Montehall_simplified
sessionID: CS201
